title: ShokuAI
description: Aplikacja mobilna
show_downloads: false

baseurl: "/ShokuAi"
url: "https://majacich.github.io"
github:
  pdf_url: "https://majacich.github.io/ShokuAi/instruction.pdf"
  apk_url: "https://majacich.github.io/ShokuAi/app-release.apk"
  prezentacja_url: "https://majacich.github.io/ShokuAi/prezentacja.pdf"

#theme: jekyll-theme-cayman-blog
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-target-blank
  - kramdown-parser-gfm

target-blank:
    rel: nofollow

header_page_refs: ['app', 'tutorial', 'contact', 'privacyPolicy', 'termsOfUse']

markdown: kramdown
